### ISSUE TITLE
Create csv endpoint with github repos that can be read by Code for All API

### ISSUE THREAD

**Issue by KrzysztofMadejski** [epforgpl/web-kodujdlapolski.pl#10]
`Projects list` as described here https://github.com/codeforamerica/cfapi#how-to-add-your-brigade-to-the-api:

Powinny być brane angielskie wersje projektów do przetwarzania, chyba że nie są zdefiniowane.

**Comment by pkliks** [comment]
@KrzysztofMadejski - nie bardzo rozumiem co miałbym to zrobić?

**Comment by KrzysztofMadejski** [comment]
Zrobić skrypt PHP dostępny z zewnątrz który będzie wypluwał plik csv.

Rekordów powinno być tyle ile linków do github wśród wszystkich projektów. 

- iterując po projektach
  - iterując po linkach
    - jeżeli link zawiera github.com to jest wypisywany rekord csv

**Comment by KrzysztofMadejski** [comment]
Celem tego jest, aby nasze projekty znalazły się na http://www.codeforamerica.org/brigade/projects

Format listy projektów organizacji: https://github.com/codeforamerica/brigade-information#projects-list)

- [ ] Muszę jeszcze ustalić, czy tworzymy jedną organizację na całe Code for Poland, czy per-brygady..

PS. Info dla wypełniających informacje (liderów spotkań i projektów): https://github.com/codeforamerica/brigade/blob/master/README-Project-Search.md#adding-a-civicjson-to-your-project

**Comment by pkliks** [comment]
@KrzysztofMadejski w na przykład "Cichy Bohater" github pojawia się w linkach 3 razy, co w takiej sytuacji?

**Comment by KrzysztofMadejski** [comment]
- [ ] W csv dodać jeszcze nagłówki jako pierwszą linię: name,description,link_url,code_url
- [ ] Aby rozróżnić wiele repozytoriów per projekt  dodajmy do nazwy w nawiasie nazwę repozytorium, czyli dla Cichego, `name = `
  - Cichy Bohater (cichybohater)
  - Cichy Bohater (cichybohater-api)
  - Cichy Bohater (cichybohater-mobile)

**Comment by KrzysztofMadejski** [comment]
Wygląda na to, że ok. Finalnie to sprawdzę, jak wepnę to API amerykańskiego.
