### ISSUE TITLE
Blog

### ISSUE THREAD

**Issue by KrzysztofMadejski** [epforgpl/web-kodujdlapolski.pl#14]

**Comment by KrzysztofMadejski** [comment]
![bloglist](https://cloud.githubusercontent.com/assets/849975/8649489/266b4af8-296b-11e5-9a22-bd8a661a2245.jpg)

![blog_post](https://cloud.githubusercontent.com/assets/849975/8649493/28d41284-296b-11e5-8be5-17a31feb9f54.jpg)

**Comment by KrzysztofMadejski** [comment]
> "lista postów danego usera - taj jak na epf, czyli widok listy postów :)" 

@ArekSoldon: tylko zamiast "Blog" bedzie "Imie Nazwisko"? Fota z prawej? Opis danej osoby zamiast kategorii?

**Comment by ArekSoldon** [comment]
![blog_author](https://cloud.githubusercontent.com/assets/3994690/8690489/5b906d94-2ab5-11e5-9f60-ec634eb9f8f8.jpg)

**Comment by KrzysztofMadejski** [comment]
Blog powinien pojawić się także na stronie brygad #23, nad partnerami, w podobnym układzie jak na stronie głównej.

**Comment by KrzysztofMadejski** [comment]
Dodatkowa kategoria `FAQ`, która będzie służyła za wiki.

**Comment by KrzysztofMadejski** [comment]
@ArekSoldon dodasz nazwy kategorii, do których przypisany jest post w widoku pojedynczego posta?

CC: @pkliks

**Comment by pkliks** [comment]
Ja bym proponował coś takiego obok daty:
![image](https://cloud.githubusercontent.com/assets/5563486/12508173/bfde128e-c0fa-11e5-8baa-ac798a53b084.png)
Co Wy na to?

**Comment by ArekSoldon** [comment]
deal, tylko czerwone bo to będzie linkiem...
