### ISSUE TITLE
Przy scrollowaniu menu przyklejać do górnej krawędzi ekranu

### ISSUE THREAD

**Issue by KrzysztofMadejski** [epforgpl/web-kodujdlapolski.pl#15]
(ze zmniejszonym logo KdP)

To zadanie opcjonalne, pytanie ile to pracy.

**Comment by pkliks** [comment]
@KrzysztofMadejski Niewiele do godziny pracy.

**Comment by KrzysztofMadejski** [comment]
Czy responsive tez jest wliczony w to? Bo teraz menu responsive z logiem zajmuje pół ekranu na moim S3. Jeżeli ma być przyklejony to trzeba by je skompaktować w responsywie.

**Comment by pkliks** [comment]
mniejsze logo i hamburger zamiast linków otwierający overlaya z menu
