### ISSUE TITLE
Justowanie opisów projektów

### ISSUE THREAD

**Issue by KrzysztofMadejski** [epforgpl/web-kodujdlapolski.pl#15]
![kdp-justowanie-tekstu-projktu](https://cloud.githubusercontent.com/assets/849975/13367662/741ea51a-dce4-11e5-95cf-5b1e8774f351.PNG)

**Comment by KrzysztofMadejski** [comment]
Propozycja:
![opis-justified](https://cloud.githubusercontent.com/assets/849975/20574986/89a0fb1a-b1b7-11e6-8ddb-474ac0b7ccfc.PNG)

**Comment by pkliks** [comment]
Tak jak przy blogu, ustawienie można nadpisać w edytorze WP
