### ISSUE TITLE
Sposoby działania w ramach KdP

### ISSUE THREAD

**Issue by KrzysztofMadejski** [epforgpl/web-kodujdlapolski.pl#18]
Propozycja zmian w layoucie:

*- mamy zdublowane teksty – nagłówek i guzik, button wyrównałbym do prawej i dał nieco inne teksty aby uzyskać równe wysokości boxów i bardziej wyraziste CTA oraz zmienił kolejność:*
![image009](https://cloud.githubusercontent.com/assets/849975/5438849/87057108-847b-11e4-9001-0dd2c4f2b0f2.png)

**Comment by ArekSoldon** [comment]
Na projekcie, copy CTA trzeba zmienić ale to już zostawiam wam :)

**Comment by pkliks** [comment]
@KrzysztofMadejski w którym miejscu miałoby się to znaleźć?

**Comment by KrzysztofMadejski** [comment]
Na głównej stronie wyłącznie.
