### ISSUE TITLE
Logo FB nie wyświetla się w niektórych przeglądarkach + ekstra linki

### ISSUE THREAD

**Issue by KrzysztofMadejski** [epforgpl/web-kodujdlapolski.pl#18]
IceWeasel (prawy div ląduje poniżej lewego)

**Comment by pkliks** [comment]
@KrzysztofMadejski dałoby radę ogarnąć screen? Nie bardzo mam dostęp do IceWeasel i nie wiem o który element chodzi.

**Comment by KrzysztofMadejski** [comment]
## Firefox 47.0.2 - działa
![firefox](https://cloud.githubusercontent.com/assets/849975/20574379/6b95b3c0-b1b4-11e6-9aa3-d3291f16c4d9.PNG)

## Chrome 54.0.2840.99 m - nie działa, schował się
![chrome-fb](https://cloud.githubusercontent.com/assets/849975/20574437/b5bddd4c-b1b4-11e6-9b83-e6d97fa96eb1.PNG)

**Comment by KrzysztofMadejski** [comment]
Poza tym prosiłbym o dodanie większej ilości linków, w sumie ten pasek powinien zawierać: ikony
- [x] IRC przeniesiony z menu tutaj z logiem http://www.43oh.com/wp-content/uploads/2010/11/msp430_ircl_channel_43oh.png
- [x] YouTube linkujący do https://www.youtube.com/playlist?list=PLa_8n5BEWSblFfplDjma-1nPGNoUqwwzL
- [x] Twitter https://twitter.com/kodujdlapolski lub https://twitter.com/codeforpoland zależnie od języka aktualnego
- [x] Facebook

**Comment by pkliks** [comment]
@KrzysztofMadejski Dodałem edycję tych linków w ustawieniach Ogólne (menu w panelu admina) oraz proponuję te ikony wziąć z Font Awesome, wtedy można dodać na hover zmianę koloru, pytanie tylko czy coś z tego zbioru: http://fontawesome.io/icons/ byłoby ok pod IRC?

**Comment by KrzysztofMadejski** [comment]
Zostawmy tego IRC z obrazkiem, bo nie znajduję w Font Awesome czegoś dedykowanego. Jak odpalimy Slacka, to bym dał ikonkę czatu, ale teraz ten IRC jest dość niszowy.

Problem: u mnie w Chrome nadal nie widać tych ikonek.

**Comment by pkliks** [comment]
@KrzysztofMadejski podaj mi jeszcze proszę pełną specyfikację, bo sprawdzam to na różnych przeglądarkach/kompach, browserstacku i wszędzie są te ikonki prawidłowo także potrzebowałbym:
1. System (w tym wersja)
2. Jaka konkretnie wersja Chrome
3. Rozdzielczość

Jak to powyżej mi nie pomoże to możliwe, że jeszcze będę potrzebować listy wtyczek zainstalowanych do chrome, bo może któraś z nich coś kopie albo chwilowy zdalny dostęp do Twojego kompa żebym mógł sobie w webdeveloperze sprawdzić o co chodzi.

**Comment by KrzysztofMadejski** [comment]
Mój błąd,  AdBlock plus  1.12.4 usuwał ikonki.
