### ISSUE TITLE
Linki nie są wyróżnione

### ISSUE THREAD

**Issue by KrzysztofMadejski** [epforgpl/web-kodujdlapolski.pl#19]
Gubią się przy innych embedach (np. [w bandzie](http://kodujdlapolski.pl/projects/band-bank-nasadzen-drzew/))

**Comment by KrzysztofMadejski** [comment]
## Wygląd przed

![linki-obecnie](https://cloud.githubusercontent.com/assets/849975/20574758/763095e6-b1b6-11e6-8260-614521ae33f6.PNG)

## Proponowany wygląd po

![link-po](https://cloud.githubusercontent.com/assets/849975/20574763/7b88a93e-b1b6-11e6-8bd3-8def17d9b9aa.PNG)

**Comment by pkliks** [comment]
Coś takiego: http://kdp.dev.inovia.pl/projects/band-bank-nasadzen-drzew/ ?

**Comment by KrzysztofMadejski** [comment]
Perfetto, może marginesy pomiędzy samymi przyciskami linków trochę mniejsze..

**Comment by pkliks** [comment]
Zmniejszone

**Comment by KrzysztofMadejski** [comment]
Github super, ale przestało embedować dyskusję na forum. 
Działa -> http://kodujdlapolski.pl/projects/politikon/
Nie działa -> http://kdp.dev.inovia.pl/projects/politikon/

Też dobrze jakby była otoczona ramką tak jak Github. U góry przycisk linkujący wyświetlający nazwę linku ustawioną w edycji. W przypadku Politikona będzie to "Dyskusja na forum"

**Comment by pkliks** [comment]
Nie wyświetliło się, bo z automatu przy przerzuceniu wszędzie kodujdlapolski.pl zmieniło się na kdp.dev.inovia.pl dla Politikona zmieniłem więc możesz już zobaczyć.
Link z tekstem otwórz w nowym oknie zostawiłem, bo to forum jest przeciętnie czytelne w tym iframe i warto zostawić ten link tam pod też.
