### ISSUE TITLE
Spersonalizowane "Skontaktuj się z koordynatorem"

### ISSUE THREAD

**Issue by KrzysztofMadejski** [epforgpl/web-kodujdlapolski.pl#20]
Żeby wiedzieć, że się pisze do konkretnej osoby.

- [x] dodać pole w edycji projektu
- [x] jak wypełnione to wyświetlać "Skontaktuj się z [Celownik imienia] - koordynatorem projektu" 
- [x] jak puste to wyświetlić "Skontaktuj się z koordynatorem"

Przed:
![kdp-koordynator](https://cloud.githubusercontent.com/assets/849975/20574856/e5d5c22c-b1b6-11e6-9dd7-ebce1d6f5a63.PNG)

Po: 
![kdp-koordynator2](https://cloud.githubusercontent.com/assets/849975/20574907/2823ddd0-b1b7-11e6-958b-a811eeda05d3.PNG)

**Comment by KrzysztofMadejski** [comment]
Przed:
![kdp-koordynator](https://cloud.githubusercontent.com/assets/849975/20574856/e5d5c22c-b1b6-11e6-9dd7-ebce1d6f5a63.PNG)

Po: 
![kdp-koordynator2](https://cloud.githubusercontent.com/assets/849975/20574907/2823ddd0-b1b7-11e6-958b-a811eeda05d3.PNG)


Moim zdaniem nie ma, aż tak dużej wartości dodanej żeby to ręcznie wpisywać w projekcie, ale może..

**Comment by pkliks** [comment]
Przykładowe z uzupełnionym imieniem: http://kdp.dev.inovia.pl/projects/strona-kodujdlapolski-pl/

**Comment by KrzysztofMadejski** [comment]
Po angielsku nie działa, później będziesz tłumaczył?

Zamień proszę "Contact with coordinator" na "Contact coordinator", a w wersji z imieniem na "Contact [imie] - project coordinator"

**Comment by pkliks** [comment]
Działa, tylko link przełączania języków kierował na codeforpoland.org - a tu zmian nie ma ;). Zmieniłem konfigurację wtyczki, także będzie już działać angielska na testowej - http://kdp.dev.inovia.pl/en/projects/strona-kodujdlapolski-pl/
