### ISSUE TITLE
Nie działa wysyłanie wiadomości do koordynatora projektu Politikon

### ISSUE THREAD

**Issue by nausicaaa** [epforgpl/web-kodujdlapolski.pl#21]
Po wypełnieniu formularza i naciśnięciu "send" nic się nie dzieje. Zakładam, że formularz wcale się nie wysyła. Chrome Version 48.0.2564.103 (64-bit)

**Comment by KrzysztofMadejski** [comment]
Przy okazji, w polskiej wersji językowej przycisk powinien mieć etykietę "Wyślij"
