### ISSUE TITLE
Strona Not Found - 404

### ISSUE THREAD

**Issue by KrzysztofMadejski** [epforgpl/web-kodujdlapolski.pl#23]
Ładniej wystylowana niż obecnie (Np. dla http://kodujdlapolski.pl/projekty/baterie-malopolska-pl/) . 

Nagłówek: "404" (może bardzo dużą czcionką) "Nie znaleziono strony"
Tekst "Przejdź do <a href> strony głównej</a>"

**Comment by pkliks** [comment]
@KrzysztofMadejski mógłbyś mi tu wrzucić screena z tego co aktualnie Ci się pojawia jak jest 404?

**Comment by KrzysztofMadejski** [comment]
Dostaję Http Error 404 bez żadnej treści co objawia się następująco:

![kdp404](https://cloud.githubusercontent.com/assets/849975/20755126/205ffee2-b70e-11e6-8a41-9c6226301577.PNG)

PS. Widzę, że na stronie jest zainstalowana wtyczka "404page - your smart custom 404 error page"

**Comment by pkliks** [comment]
No własnie to nie jest normalne. Przy braku ustawienia powinien się index z motywu ładować. Dzięki za info o tej wtyczce skróci mi czas szukania co powoduje ten problem ;)

**Comment by pkliks** [comment]
http://kdp.dev.inovia.pl/asdsadsad/ 

Pytanie czy partnerzy ze stopki mają zostać czy tutaj ich ukryć?

**Comment by KrzysztofMadejski** [comment]
Partnerzy zostają.

Zlokalizuj proszę "Go to homepage" na "Przejdź do strony głównej"
