### ISSUE TITLE
Strona Brygad

### ISSUE THREAD

**Issue by KrzysztofMadejski** [epforgpl/web-kodujdlapolski.pl#23]
Alfabetyczna kolejność miast,
miejska fotka Poznania?

A może mapa Polski? @mszkodzinski?

**Comment by KrzysztofMadejski** [comment]
Arek, mapka?

Kafelek "Załóż CityLab w swoim mieście" odpalający formularz to też super pomysł.

**Comment by ArekSoldon** [comment]
![brygady](https://cloud.githubusercontent.com/assets/3994690/8690670/ec044e84-2ab7-11e5-8637-511de9d3b727.jpg)

**Comment by KrzysztofMadejski** [comment]
- [ ] Copy "Chcesz prowadzić City Lab w swoim mieście? Napisz do nas!"
- [ ] nazwa w formacie "City Lab Warszawa", nie na odwrót
- [ ] do profilu CityLabu musi dojść dodanie lokalizacji

**Comment by ArekSoldon** [comment]
![citylaby](https://cloud.githubusercontent.com/assets/3994690/8925090/1121e35a-3505-11e5-8974-a1f3dd27b314.jpg)

**Comment by ArekSoldon** [comment]
![citylaby](https://cloud.githubusercontent.com/assets/3994690/8925149/b467cb1a-3505-11e5-9f43-95ca2e34ca08.jpg)
