### ISSUE TITLE
Sortowanie projektów

### ISSUE THREAD

**Issue by KrzysztofMadejski** [epforgpl/web-kodujdlapolski.pl#24]
Na początek te z `Status prac = aktywny rozwój` poźniej `Zawieszone`, w drugiej kolejności sortowania te które `Status projektu = funkcjonujące` , poźniej `Publiczne testy` i `Rozwój`. 
Tak aby na początek szły te AktywnyRozwój+Funkcjonujące, a później AktywnyRozwój+PubliczneTesty itd.

http://kodujdlapolski.pl/en/projects

**Comment by pkliks** [comment]
Nie wszystkie mają oba statusy ustawione, wtedy lądują na końcu (najlepiej uzupełnić)
