### ISSUE TITLE
Na stronie brygady: beleczki przy "Koordynatorzy" i "Projekty" + pobieranie osób

### ISSUE THREAD

**Issue by KrzysztofMadejski** [epforgpl/web-kodujdlapolski.pl#25]
Albo w jakiś inny sposób wyróżnić te sekcje.
![image015](https://cloud.githubusercontent.com/assets/849975/5439024/c2fd487e-847c-11e4-8f14-65196f4c9741.png)

**Comment by pkliks** [comment]
@KrzysztofMadejski "Zamienić na CityLab." - co zamienić na citylab?

**Comment by KrzysztofMadejski** [comment]
To jeszcze musze przemyśleć, dam znać w środę.
