### ISSUE TITLE
Tłumaczenie funkcji ogólnych oraz opisów użytkowników na angielski

### ISSUE THREAD

**Issue by KrzysztofMadejski** [epforgpl/web-kodujdlapolski.pl#25]
Tłumaczenie np. "Koordynator ogólnopolski"
oraz "Koordynuje program Koduj dla Polski, zarządza projektami technologicznymi" na http://codeforpoland.org/author/krzysztof_madejski/

Dwa nowe pola w profilu użytkownika.

**Comment by pkliks** [comment]
http://kdp.dev.inovia.pl/en/author/krzysztof_madejski/

**Comment by KrzysztofMadejski** [comment]
Ta funkcja też powinna być lokalizowana na stronie Kontakt: http://kdp.dev.inovia.pl/en/contact/ (zapomniałem o tym).
