### ISSUE TITLE
Partnerzy - sortowanie i formatowanie

### ISSUE THREAD

**Issue by KrzysztofMadejski** [epforgpl/web-kodujdlapolski.pl#27]
- kolejność: na górze ‘generalni’, potem miasta alfabetycznie
- zmienić styl nagłówków na beleczki

![image010](https://cloud.githubusercontent.com/assets/849975/5439084/311a3722-847d-11e4-9430-6402c6e4a9f9.png)

**Comment by Cain-Ish** [comment]
Fix polish order
