### ISSUE TITLE
Wiki

### ISSUE THREAD

**Issue by KrzysztofMadejski** [epforgpl/web-kodujdlapolski.pl#29]
z informacjami 
- jak dołączyć
- faq
- rózne poradniki
- ale także organizacja hakatnów

**Comment by pkliks** [comment]
@KrzysztofMadejski  - możesz mi to dokładniej rozpisać? Jakiś przykład?

**Comment by KrzysztofMadejski** [comment]
Odpuscmy to, zrealizujemy wiki w postaci artykułów na blogu, z nową kategorią FAQ
