### ISSUE TITLE
Mozilla: avatar blank się nie pokazuje

### ISSUE THREAD

**Issue by KrzysztofMadejski** [epforgpl/web-kodujdlapolski.pl#3]
![kdp-blank](https://cloud.githubusercontent.com/assets/849975/13367359/41757c58-dce2-11e5-89e6-3fe2cda7f1e3.PNG)

Skąd taki dziwny link? http://2.gravatar.com/avatar/bc908cc5e339450ba916a798f72b81cb?s=105&amp;d=http%3A%2F%2Fnew.kodujdlapolski.pl%2Fwp-content%2Fthemes%2Fkdp%2Fimages%2Fblank-person.png&amp;r=g

Dlaczego nie po prostu http://kodujdlapolski.pl itd.?

**Comment by pkliks** [comment]
Ponieważ gravatar zawsze zwraca jakiś adres, także ustawiłem ten KdP blank jako domyślny i jeśli nie było ustawionego zdjęcia w WP to ładował z gravatara ustawiony lub blanka. Dodałem warunek że jeśli w gravatarze jest blank to ładuje blanka z lokalnego serwera

EDIT: warunek nie spełnił swojego zadania

**Comment by pkliks** [comment]
Ok, działa. Idzie przez gravatar z wyżej wymienionego powodu, ale poprawiłem adres (miał zapamiętany z new.kodujdlapolski.pl dlatego nie działało)
