### ISSUE TITLE
Wyświetlanie Issues jest na sztywno zaszyte pod to repo, zamiast dynamicznego pobierania zgodnie z linkiem do Github

### ISSUE THREAD

**Issue by KrzysztofMadejski** [epforgpl/web-kodujdlapolski.pl#30]
Np. http://kodujdlapolski.pl/projects/streetmix-net-po-polsku/ powinno wyświetlać Issues z https://github.com/codeforamerica/streetmix/issues/ (link "Zobacz więcej" dobrze działa

Zgłoszone tu https://twitter.com/danek_szy/status/758669146196480000

**Comment by danekszy** [comment]
https://github.com/epforgpl/web-kodujdlapolski.pl/blob/2a875e2f557ea33890d8b8f0f7f819139144e4db/single-projects.php#L182
Problemem zdaje się być zakomentowana niewłaściwa linia, aczkolwiek nie znam podłoża sprawy ani ew. motywu takiego działania. Być może jest to celowe, wiec nie zgłaszam PR-a, tym bardziej, że jest to raczej mała zmiana...

**Comment by KrzysztofMadejski** [comment]
To jakaś pozostałość po debuggowaniu pewnie. Dzięki za wskazanie miejsca, już poprawiłem. Po 12h cache się wyczyści i wszytkie projekty powinny mieć aktualne issues.
