### ISSUE TITLE
Rejestracja nowych użytkowników

### ISSUE THREAD

**Issue by KrzysztofMadejski** [epforgpl/web-kodujdlapolski.pl#35]
Umożliwić rejestrację nowych użytkowników i poprawić formularz rejestracji:

![kodujdlapolski-rejestracja](https://cloud.githubusercontent.com/assets/849975/20571176/b0d40c1a-b1a6-11e6-8a78-442e37f9df84.PNG)

- [x] pierwsze pole nazywa się email, a to tak naprawdę nazwa użytkownika, niech nazwa usera będzie tworzona automatycznie na podstawie emaila
- [x] pola Funkcja, Telefon, i Email kontaktowy niech nie pokazują się w formularzu rejestracji
- [x] niech będzie można podać Imię i Nazwisko, Email, Zdjęcie

**Comment by pkliks** [comment]
Doszła też wtyczka do edycji treści maila powitalnego - Ustawienia -> SB Welcome Email (ważne, że nie podawać tam jako loginu faktycznego loginu tylko zawsze e-mail, sam login w bazie nie może być równy mailowi, zawiera wtedy niedozwolone znaki)

**Comment by KrzysztofMadejski** [comment]
Potrzebna tu będzie captcha, bo już z automatu tworzeni są jacyś użytkownicy. (z automatu bo w domenie spamavert.com).
