### ISSUE TITLE
Zmiana języka PL/EN

### ISSUE THREAD

**Issue by KrzysztofMadejski** [epforgpl/web-kodujdlapolski.pl#35]
Implementacja: tak, żeby łatwo się można było przełączać między różnymi językami danego posta i żeby było widać, że danego posta brakuje w innej wersji językowej (czyli raczej nie multisite, jeśli moja wiedza o WP jest dobra)

**Comment by KrzysztofMadejski** [comment]
Layout na #36

**Comment by KrzysztofMadejski** [comment]
@pkliks A jak będą zrealizowane tłumaczenia wszystkich statycznych tekstów? Będą edytowalne?

**Comment by pkliks** [comment]
Korzystam z wtyczki wpml umożliwia powiązanie postów/stron pomiędzy językami, co do tekstów w kodzie to też jest to obsłużone, tylko trzeba każdy tekst odpowiednio okodować, co będzie najbardziej czasochłonne jeśli chodzi to zadanie.

Co do wtyczki - jest płatna, mam wykupioną licencję developerską także może spokojnie być na mojej licencji jeśli chodzi o update'y
