### ISSUE TITLE
Strona partnerów

### ISSUE THREAD

**Issue by KrzysztofMadejski** [epforgpl/web-kodujdlapolski.pl#37]
Przebudować stronę partnerów (http://kodujdlapolski.pl/partnerzy/), tak żeby obok każdego loga pojawiał się opis tego partnera w kontekcie KdP. 

Jeden partner horyzontalnie?

Tekstu około 50-80 słów:
> Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum pellentesque, diam eu consectetur volutpat, nibh tellus suscipit lorem, eget maximus mi tellus eu quam. Etiam feugiat interdum tempus. Nullam at tortor ornare, luctus arcu quis, posuere arcu. Aliquam risus tortor, convallis non tellus et, tempus commodo justo. Ut tempor odio felis, rhoncus vestibulum tortor efficitur ut. Nullam sit amet fringilla enim. Mauris id varius elit. Suspendisse tincidunt orci eu elementum finibus. Suspendisse sed pellentesque est. Sed tincidunt nulla velit, quis.

**Comment by ArekSoldon** [comment]
![partnerzy](https://cloud.githubusercontent.com/assets/3994690/8690797/55f27c70-2ab9-11e5-872a-bf31bbd6e687.jpg)

**Comment by KrzysztofMadejski** [comment]
@ArekSoldon:  Horyzontalnie byłoby lepiej, jeden partner per wiersz, kilka moich propozycji poniżej.

![55f27c70-2ab9-11e5-872a-bf31bbd6e687-2](https://cloud.githubusercontent.com/assets/849975/8801553/e4d5e0e2-2fbb-11e5-81bb-f877c1b401ed.jpg)

**Comment by ArekSoldon** [comment]
![partnerzy](https://cloud.githubusercontent.com/assets/3994690/8925110/69653544-3505-11e5-8372-1662f10cd9ef.jpg)

**Comment by KrzysztofMadejski** [comment]
- [ ] Dodać podział na sekcje: wybieranie z listy, które zbiory partnerów są wyświetlane (Koordynacja, Organizatorzy lokalni, Lokale goszczące, itp. tid.)

**Comment by KrzysztofMadejski** [comment]
Finalnie:
![img](https://cloud.githubusercontent.com/assets/3994690/11951585/6cf1b542-a892-11e5-9d4f-b5ee9d62aeb1.jpg)
