### ISSUE TITLE
Issus'y z githuba powinny przenosić na strone github a nie odwoływać się do api

### ISSUE THREAD

**Issue by ghostbuster91** [epforgpl/web-kodujdlapolski.pl#40]

**Comment by KrzysztofMadejski** [comment]
@pkliks to tak nie działało?

**Comment by KrzysztofMadejski** [comment]
Przykład: ze strony https://kodujdlapolski.pl/projects/wtyczki-demagoga/ issues linkują np. do https://api.github.com/repos/kodujdlapolski/factchecker-plugin-chrome/issues/30
