### ISSUE TITLE
Na stronie Brygady Poznań projekt(y) nie renderują się poprawnie

### ISSUE THREAD

**Issue by magul** [epforgpl/web-kodujdlapolski.pl#43]
Na stronie Brygady Poznań (http://kodujdlapolski.pl/brygady/poznan/) jedyny obecnie projekt błędne się renderuje.

Dla przykładu projekty na stronie http://kodujdlapolski.pl/brygady/krakow/ umieszczają się poprawnie.

![brygadapoznan](https://cloud.githubusercontent.com/assets/1165138/10347898/6f9080cc-6d36-11e5-837d-03881bfe4357.png)

**Comment by magul** [comment]
Dobra, doszedłem czemu tak się dzieje - wygląda na to, że do brygady musi należeć jeszcze osoba, która nie istnieje. Po wstawieniu jako admin kolejnej, nieuzupełnionej osoby wszystko renderuje się poprawnie.

Mam workaround, więc dla mnie można zamknąć.

**Comment by KrzysztofMadejski** [comment]
Zamykam! PS. Będziemy odświeżać stronę.
