### ISSUE TITLE
Layouty - poprawki

### ISSUE THREAD

**Issue by KrzysztofMadejski** [epforgpl/web-kodujdlapolski.pl#47]
Do dodania:
- [ ] rozwinąć stronę użytkownika - #46
- [ ] podział partnerów na sekcje - #47
- [ ] na stronie miasta wyciąganie najbliższych wydarzeń
- [ ] projekty - kategorie i filtrowanie tak jak na transparencee (technologia, status projektu, ... )
- [ ] na stronie głównej w PDF nie widzę informacji o najbliższych spotkaniach - teraz trzeba by wyswietlać listę kilku bo się dzieją równolegle

**Comment by ArekSoldon** [comment]
rozwinąć stronę użytkownika - #46
![user](https://cloud.githubusercontent.com/assets/3994690/11696898/0c8f2480-9eb7-11e5-8a01-9372a5f1128b.jpg)


 podział partnerów na sekcje - #47
jakie sekcje? czy zostajemy przy liście jeden pod drugim? 

 na stronie miasta wyciąganie najbliższych wydarzeń
ale to jest już :) 
http://kodujdlapolski.pl/brygady/warszawa/


 projekty - kategorie i filtrowanie tak jak na transparencee (technologia, status projektu, ... )
![projekty](https://cloud.githubusercontent.com/assets/3994690/11696999/b4a479e0-9eb7-11e5-9289-292a374c0317.jpg)


 na stronie głównej w PDF nie widzę informacji o najbliższych spotkaniach - teraz trzeba by wyswietlać listę kilku bo się dzieją równolegle

to było już kiedyś, teraz trzeba po prostu dać opisy miast mniejsze... 
![main_2015](https://cloud.githubusercontent.com/assets/3994690/11696768/4bbe5e56-9eb6-11e5-9e1c-aa082646cd17.jpg)

**Comment by KrzysztofMadejski** [comment]
Partnerzy:
- zostajemy przy liście jeden pod drugim
- [ ] tą listę rozdzielamy na sekcje definiowane z admina (organizator, organizatorzy spotkań, .. - teraz jest podobnie: http://kodujdlapolski.pl/partnerzy/)

Strona użytkownika:
- [ ] czy tytuły sekcji "Zaangażowany w projekty", "Wpisy" nie są zbyt mało wyróżnione?
- [ ] nie potrzebujemy podziału wpisów na kategorie w tym miejscu

Wyciąganie spotkań na stronie lokalnej - jest faktycznie, mój błąd!

Projekty - super!

Najbliższe spotkania:
- sugeruje, że 24 czerwca jest w kilku miastach (co będzie się zdarzać, pytanie, czy inne miasta dzięki temu nie ucierpią, jeżeli np. przez większość tygodnia będzie się wyświetlać tylko poniedziałkowe Krakowskie? Z drugiej strony to podkreślenie najbliższego wyraźną datą jest fajne.
- gdyby tak zrobić listę trzech najbliższych, każde w nowej linii:
  - 24.06 - Kraków 
  - 25.06 - Warszawa
  - 25.06 - Warszawa
- przygotujesz taką wizkę? Które rekomendujesz?

**Comment by ArekSoldon** [comment]
![partnerzy](https://cloud.githubusercontent.com/assets/3994690/11951585/6cf1b542-a892-11e5-9d4f-b5ee9d62aeb1.jpg)
![main](https://cloud.githubusercontent.com/assets/3994690/11951587/6cf49438-a892-11e5-90c6-b69995736c9b.jpg)
![user](https://cloud.githubusercontent.com/assets/3994690/11951586/6cf3adc0-a892-11e5-8b2c-24e1cfa3f7a6.jpg)

psd
https://dl.dropboxusercontent.com/u/19244622/main_2015.psd.zip
