### ISSUE TITLE
Lokalne spotkania - link do grupy FB i Meetup

### ISSUE THREAD

**Issue by KrzysztofMadejski** [epforgpl/web-kodujdlapolski.pl#50]
Teraz naszło mnie (excusez-moi), że brakuje na stronie brygady konkretnej (np. http://kodujdlapolski.pl/brygady/warszawa/) powyższych serwisów, na których zbieramy ludzi zaangażownych. Myślę, że fajnie to by się zmieściło pod kafelkiem "Najbliższe spotkanie" jako dwa nowe kafelki: "Zapisz się na Meetup" -> http://www.meetup.com/Koduj-dla-Polski-Warszawa/ oraz "Dyskutuj na FB" -> https://www.facebook.com/groups/kodujdlapolski.warszawa (przykład dla Warszawy). Z grup FB można by zaciągać zdjęcia tła, jeżeli to się wpasowuje. Jako kafelek Meetup-a może logo?

**Comment by ArekSoldon** [comment]
![fb2](https://cloud.githubusercontent.com/assets/3994690/12448718/4f0b5a04-bf78-11e5-99f9-8a57261b40b1.jpg)
![meetup](https://cloud.githubusercontent.com/assets/3994690/12448717/4f0678e0-bf78-11e5-8e17-457f8b03c316.jpg)
![fb](https://cloud.githubusercontent.com/assets/3994690/12448719/4f0b794e-bf78-11e5-9237-8f130e11f649.jpg)

**Comment by KrzysztofMadejski** [comment]
I jeszcze tekściki by się przydały na tych banerach:
- "Dyskutuj na FB"
- "Śledź spotkania na Meetup"

**Comment by ArekSoldon** [comment]
tekściki wrzuca Kliksior w htmlu :)

**Comment by KrzysztofMadejski** [comment]
Do dorzucenia na stronie brygady pojedynczej pod kafelkiem "Najbliższe spotkanie". W panelu admina powinny dojść dwa pola na linki.
FB - kafelek niebieski
