### ISSUE TITLE
Wyświetlanie statystyk z Github na projekcie

### ISSUE THREAD

**Issue by KrzysztofMadejski** [epforgpl/web-kodujdlapolski.pl#51]
Języki wykorzystywane https://api.github.com/repos/KlubJagiellonski/Politikon/languages
![github-languages](https://cloud.githubusercontent.com/assets/849975/12431082/b74a5ae6-bef3-11e5-9a29-d9775220e569.PNG)

Recent issues - https://api.github.com/repos/KlubJagiellonski/Politikon/issues
![github-issues](https://cloud.githubusercontent.com/assets/849975/12431358/5a7ebc4c-bef5-11e5-98d2-3017c16fda4a.PNG)

Ostatnie commity - https://api.github.com/repos/KlubJagiellonski/Politikon/commits
![github-recent-commits](https://cloud.githubusercontent.com/assets/849975/12431101/c6764c32-bef3-11e5-8ee9-8f15b13c6a26.PNG)

**Comment by pkliks** [comment]
@KrzysztofMadejski co z tego chcesz i w jakiej formie żeby w ramach projektu było wyświetlane?

**Comment by KrzysztofMadejski** [comment]
@pkliks:
- języki wykorzystywane tak jak widać
- issues - wyświetlić max 3 otwarte + przycisk see more kierujący do linka githubowego + `/issues`. Wygląd: Same issuesy, bez filtrów, najlepiej żeby wyglądały tak jak na github. Szukałem widgetów, ale nie znalazłem..
- commits - 3 ostatnie
- pod spodem link 'Go to Github/Przejdź do Github'
- nad tym wszystkim nazwa repo zaciągana z github

Wolisz, żeby @ArekSoldon zaprojektował całość przed cięciem?

**Comment by pkliks** [comment]
@KrzysztofMadejski propozycja: http://koduj.dev.inovia.pl/projects/cichy-bohater/ (issues zaciągają się z web-kodujdlapolski.pl jak będzie ok to zmienię żeby pobierało normalnie dla tego projektu. Daj znać czy taka forma prezentacji będzie ok no i żeby @ArekSoldon Ewentualnie podrasował

**Comment by KrzysztofMadejski** [comment]
Trochę sucho to wygląda. @ArekSoldon, jakieś pomysły?
- [ ] wywaliłbym beleczkę czarną spod języków
- [ ] daty formatować jako "5 February/Feb 2015", dodać w issues czas aktualizacji, aby był tekst `#10 opened on 12 Dec 2014 by KrzysztofMadejski  updated 2 days ago`
- [ ] w commitach dodać avatary osób
- [ ] na przyciskach można dać tytuł linku - "Github - Android" zamiast "Go to Github"
- [ ] "link Wątek na forum" tam ginie, może dać wszystkie linki jako buttons, rozdzielić to jakoś? To wyzwanie, żeby dobrze wyglądało i przy embedowaniach i przy prostej liście linków. @ArekSoldon ?

**Comment by pkliks** [comment]
@KrzysztofMadejski 

> wywaliłbym beleczkę czarną spod języków

to nie czarna belka tylko ten pasek procentowy, umknęło mi dopisanie pytania: według jakiego klucza dawać kolory językom

**Comment by ArekSoldon** [comment]
link Wątek na forum" tam ginie, może dać wszystkie linki jako buttons, rozdzielić to jakoś? To wyzwanie, żeby dobrze wyglądało i przy embedowaniach i przy prostej liście linków. @ArekSoldon ?

bo jak nawaliliśice tyle treści to co ma nie ginąć?! 
Po co ten fb tam? 

czy tego gita nie da się zrobić jednego dla wszystkich a nie 3-4 ? 

i jak już chcecie wszystkie embeddy (choć nie wiem czemu ma służyć ten z gita...) to forum też by wypadało :)

**Comment by KrzysztofMadejski** [comment]
Github ma zaszyte na stałe, u nas możemy losować z jakiejś palety. Beleczkę proponuję i tak wywalić.

@ArekSoldon gita jednego się nie da. Forum będzie. :P Jest opcja, żeby wyłączyć poszczególne embedy.

**Comment by pkliks** [comment]
@KrzysztofMadejski co z forum chcesz mieć w embedzie?

**Comment by KrzysztofMadejski** [comment]
https://www.discourse.org/about/
> Blog Integration
   Use our [WordPress plugin](https://github.com/discourse/wp-discourse) to integrate a Discourse community into your blog. Or embed Discourse into [static HTML sites](https://meta.discourse.org/t/embedding-discourse-comments-via-javascript/31963).

W embedzie chciałbym mieć konkretny wątek. Co dokładnie ma umożliwiać embed - tu już bym pozostał przy tym co jest out-of-the box z pluginu do wp.

**Comment by pkliks** [comment]
Tego pluginu to tak out of the box raczej nie będziemy w stanie użyć, raczej bym się skłaniał ku tej drugiej opcji z embedem javascriptowym, tylko tutaj trzeba wykonać pewne działania po stronie admina forum: https://meta.discourse.org/t/embedding-discourse-comments-via-javascript/31963 -> Configuring Discourse for Embedding (simple setup) - mógłbyś zerknąć i przygotować żebym mógł przetestować?

**Comment by KrzysztofMadejski** [comment]
Dodałem embeddable host, żeby poprawnie CORS obsługiwał. Usera nie uzupełniałem, bo ten kodma korzystać z istniejących wątków, a nie tworzyć nowe.

Jako `topicId` powinieneś pewnie podać to co się znajduje po slug, czyli z `https://forum.kodujdlapolski.pl/t/gry-charytatywne-implementacja/2444/29` powinno być wybrane `2444`, 3 element z path (bo przeważnie nie będzie końcowego /29). Daj znać czy chodzi

**Comment by pkliks** [comment]
Coś jednak chyba nie śmiga bo: 
![image](https://cloud.githubusercontent.com/assets/5563486/13112398/c6c33a80-d58a-11e5-8c49-351c318a328f.png)

**Comment by KrzysztofMadejski** [comment]
Poprawione.
