### ISSUE TITLE
Embeddowanie prezentacji z Google

### ISSUE THREAD

**Issue by KrzysztofMadejski** [epforgpl/web-kodujdlapolski.pl#54]
https://docs.google.com/presentation/d/1LzHnJbhII0i14dqo-sJc_l0f-oPM2cdYfqWeqIeRc7Y/edit -> 
https://docs.google.com/presentation/d/1LzHnJbhII0i14dqo-sJc_l0f-oPM2cdYfqWeqIeRc7Y/embed

```
<iframe src="https://docs.google.com/presentation/d/1LzHnJbhII0i14dqo-sJc_l0f-oPM2cdYfqWeqIeRc7Y/embed?start=false&loop=false&delayms=10000" frameborder="0" width="960" height="749" allowfullscreen="true" mozallowfullscreen="true" webkitallowfullscreen="true"></iframe>
```

**Comment by pkliks** [comment]
@KrzysztofMadejski który adres będzie podawany? ten z embed czy ma lecieć po strongu i zmieniać edit na embed?

**Comment by KrzysztofMadejski** [comment]
https://docs.google.com/presentation/d/1LzHnJbhII0i14dqo-sJc_l0f-oPM2cdYfqWeqIeRc7Y

Niech sprawdza czy się konczy na embed czy edit, jak edit to niech zmieni.
