### ISSUE TITLE
Embeddowanie FB na Firefoxie

### ISSUE THREAD

**Issue by KrzysztofMadejski** [epforgpl/web-kodujdlapolski.pl#55]
Wywala mi się z komunikatem: `Zasób pod adresem „http://connect.facebook.net/pl_PL/sdk.js#xfbml=1&version=v2.5&appId=155938441448129” został zablokowany, ponieważ jest włączona ochrona przed śledzeniem.[Więcej informacji](https://developer.mozilla.org/pl/Firefox/Privacy/Tracking_Protection) cichy-bohater`

http://koduj.dev.inovia.pl/projects/cichy-bohater/

Na pierwszy rzut oka stawiam, że to dlatego, że w tym linku do fb nie ma https

**Comment by pkliks** [comment]
Nie, to akurat kwestia tego, że Firefox w trybie prywatnym blokuje takie zasoby 
>Starting in version 42, Firefox Desktop and Firefox for Android include built-in tracking protection. In Private Browsing windows (tabs, in Firefox for Android), Firefox will block content loaded from domains that track users across sites.

Więcej tutaj: https://developer.mozilla.org/pl/Firefox/Privacy/Tracking_Protection

**Comment by KrzysztofMadejski** [comment]
Dzięki za info! Nawet nie mam prywatnego, ale musiałem odpalić jakiś do not track, czy coś.
