### ISSUE TITLE
Blog - tytuł

### ISSUE THREAD

**Issue by KrzysztofMadejski** [epforgpl/web-kodujdlapolski.pl#6]
Przeniesienie tytułu do góry, jako najważniejszego.

Baner wyrównany z autorem.

Np. tu: http://kodujdlapolski.pl/zostan-organizatorem/
![kdp-blog-top](https://cloud.githubusercontent.com/assets/849975/13367471/3941deea-dce3-11e5-97fa-59a5b1eadebf.PNG)

**Comment by ArekSoldon** [comment]
To przestawak w kodzie na minutę dla kliksa, czy chcesz wizualkę?

**Comment by KrzysztofMadejski** [comment]
Przestawak raczej, chciałem twoją aprobatę przed wdrożeniem.

I gdzie wtedy "10 lutego 2016 | Spotkania" powinien wylądować?

**Comment by ArekSoldon** [comment]
![screen-shot-2016-03-01-at-10 50 37](https://cloud.githubusercontent.com/assets/3994690/13423567/eae9f6cc-df9b-11e5-8666-d3e47f0fe676.png)

**Comment by KrzysztofMadejski** [comment]
Dzięki!

**Comment by pkliks** [comment]
@KrzysztofMadejski pierwszy akapit zmniejszyć i pogrubić jak na tym co Arek wrzucił?

**Comment by KrzysztofMadejski** [comment]
Tak, poproszę!
