### ISSUE TITLE
Pojedynczy komunikat na organizację brygady

### ISSUE THREAD

**Issue by KrzysztofMadejski** [epforgpl/web-kodujdlapolski.pl#8]
![kdp-organizuj](https://cloud.githubusercontent.com/assets/849975/13367544/974ef2e8-dce3-11e5-9d1d-13ebf971a762.PNG)

Zamiana na "Organizuj spotkania w swoim mieście!" / "Organize events in your city!" 
link: mailto:kontakt@kodujdlapolski.pl?subject=Chcę organizować spotkania w moim mieście

**Comment by KrzysztofMadejski** [comment]
U mnie (Chrome) padding jest za mały i "w" się do brzegu przykleja. A może brake twardy przed "w" lepszy?

![padding](https://cloud.githubusercontent.com/assets/849975/20972814/6796fdaa-bc96-11e6-844c-337e3560f532.PNG)

**Comment by pkliks** [comment]
Padding będzie tu lepszy na ewentualne zmiany w przyszłości
